<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.jlshell.plugins</groupId>
        <artifactId>jlshell-plugins-parent</artifactId>
        <version>0.1.0.RELEASE</version>
    </parent>

    <artifactId>plugin-session-demo</artifactId>
    <name>JLShell Session Plugin Demo</name>

    <properties>
        <jlshell.plugin.id>com.jlshell.demo.session-tools</jlshell.plugin.id>
        <jlshell.plugin.version>0.1.0</jlshell.plugin.version>
        <jlshell.plugin.scope>SESSION</jlshell.plugin.scope>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.oomn.jlshell</groupId>
            <artifactId>plugin-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
